#  --------------------------------------------------------------
#  |                  EndermanEscapeCanceller               　  |
#  |                                                            |
#  |                     Author : huda0209                      |
#  |                     Depend :                               |
#  |GitHub : https://github.com/huda0209/EndermanEscapeCanceller|
#  |                     ran by paper 1.13                      |
#  --------------------------------------------------------------


EnderManEscapeCancellMode: true


WorldName: