#  -------------------------------------------------------------
#  |                  EndermanEscapeCanceller                  |
#  |                                                           |
#  |                     Author : huda0209                     |
#  |                     Depend :                              |
#  |  GitHub :                                                 |
#  |https://github.com/stella-server-mc/IronGolemSpawnCanceller|
#  |                    ran by spigot 1.13                     |
#  -------------------------------------------------------------


EnderManEscapeCancellMode: true


WorldName: